### ISSUE TITLE
Warning: Cannot call method 'split' of undefined

### ISSUE THREAD

**Issue by jonesmac** [neoziro/grunt-shipit#39]
I have installed shipit and grunt is successfully finding my task so I know its registered.  However, no matter what I do to my options, it always comes back with 

"Warning: Cannot call method 'split' of undefined"

All my local dependences are up to date and I have this project currently working with Capistrano so I know my git setup is correct.  Any thoughts?

**Comment by jonesmac** [comment]
After some digging, I found that the issue is how I load my tasks.  Currently, I load them with 
```javascript
var config = {
		pkg: require('./package')
	};

	grunt.util._.extend(config, loadConfig('./tasks/options/'));

	// Load project configuration
	grunt.initConfig(config);
```
(This method is used in my framework from - https://github.com/use-init/init)

When I use this method, I receive a stack trace like so
TypeError: Cannot call method 'split' of undefined
    at /Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt-shipit/lib/ssh/connection-pool.js:27:31
    at Array.map (native)
    at new ConnectionPool (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt-shipit/lib/ssh/connection-pool.js:25:29)
    at Shipit.initSshPool (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt-shipit/lib/shipit.js:66:18)
    at Shipit.initialize (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt-shipit/lib/shipit.js:55:15)
    at Object.<anonymous> (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt-shipit/tasks/shipit.js:33:8)
    at Object.thisTask.fn (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/grunt/task.js:82:16)
    at Object.<anonymous> (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/util/task.js:301:30)
    at Task.runTaskFn (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/util/task.js:251:24)
    at Task.<anonymous> (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/util/task.js:300:12)
    at Task.start (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/util/task.js:309:5)
    at Object.grunt.tasks (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/grunt.js:164:8)
    at Object.module.exports [as cli] (/Users/jonesmac82/Sites/DXY/Bendix/website/node_modules/grunt/lib/grunt/cli.js:38:9)
    at Object.<anonymous> (/Users/jonesmac82/npm/lib/node_modules/grunt-cli/bin/grunt:45:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

If I use grunt.initConfig as is states in your docs it all works fine.  

As I dig further, the issue appears around line 77 of lib/shipit.js

```javascript
Shipit.prototype.initConfig = function (config) {
	console.log(config);
  this.config = extend({
    branch: 'master',
    keepReleases: 5
  }, config.options, config[this.stage]);
	console.log(this);
  return this;
};
```
I logged the config object with both methods and the return value has a different config object.  In my current setup, it never updates the config object with the settings from my task but only the defaults.  When I load it with your method, all the settings are there.  In both methods, the config settings are present in tasks/shipit.js in line 28 before the initConfig method is called.

Mine - 
```javascript
config: { branch: 'master', keepReleases: 5 } }
```
Yours - 
```javascript
config: 
   { branch: 'master',
     keepReleases: 3,
     workspace: '/tmp/build',
     deployTo: '/path/to/stage',
     repositoryUrl: 'git:myrepo',
     ignores: [ '.git', 'node_modules' ],
     servers: [ 'user@server' ] } }
```

Strange stuff I know.  I really like your module and would love to ditch my ruby dependance on capistrano.  Let me know if you have any ideas on alternate ways to load to task so the config parameters are passed correctly.

**Comment by neoziro** [comment]
@jonesmac I think you forgot to initialize shipit using the `shipit:env` task.

**Comment by jonesmac** [comment]
Thanks @neoziro

Here is my shipit task:
```javascript
/**
 * Deploy Builds
 */
'use strict';

var config = require('../config');

module.exports = {
	shipit: {
		options: {
			branch: 'master',
                        keepReleases: 3,
                        workspace: '/tmp/build',
                        deployTo: '/path/to/stage',
                        repositoryUrl: 'git:myrepo',
                        ignores: [ '.git', 'node_modules' ],
                        staging: {
                             servers: [ 'user@server' ] 
                        }
                 }
         }
};
```
And I call it with 
grunt shipit:staging deploy which gives the method 'split' of undefined error.

Did I miss something?  It seems like I am just doing something simple incorrectly.

**Comment by neoziro** [comment]
I think it's a problem in the loading of your configuration.

**Comment by awc737** [comment]
I get the same error, but with a different approach. I'm trying to setup a default deploy task, should something like this be possible?

grunt.registerTask('deploy', ['shipit:production deploy']);

Thanks

**Comment by neoziro** [comment]
You can't do it. And it's not recommended because it's always a good thing to specify the enviroment.

**Comment by neoziro** [comment]
@awc737 I close it.
